### ISSUE TITLE
UI Implementation of 'Timetable screen' and 'Add Timetable' screen

### ISSUE THREAD

**Issue by ManjunathRK1251** [gdsc-jssstu/student_study_manager#1]

**Comment by UtkarshDeoli** [comment]
can i do this

**Comment by ShivamMenda** [comment]
@UtkarshDeoli I'll assign this to you too but please make sure to complete the issues once assigned.

**Comment by ShivamMenda** [comment]
This issue has been resolved. All changes were made.
