### ISSUE TITLE
UI implementation of 'Reminders screen' and 'Add reminders' screen

### ISSUE THREAD

**Issue by ManjunathRK1251** [gdsc-jssstu/student_study_manager#2]

**Comment by ShivamMenda** [comment]
@mufida1018 Sure go ahead! Refer to the UI given in the readme file!

**Comment by ShivamMenda** [comment]
@mufida1018 Any Update?

**Comment by mufida1018** [comment]
working on it

**Comment by ShivamMenda** [comment]
@mufida1018 Sure! Open a PR when you're ready

**Comment by mufida1018** [comment]
Hey,
Pls check

**Comment by ShivamMenda** [comment]
#15

**Comment by ShivamMenda** [comment]
@mufida1018 Please check your PR review I've suggested some changes. Please do finish it by tomorrow so I can merge.

**Comment by mufida1018** [comment]
Sure

**Comment by ShivamMenda** [comment]
This issue has been resolved!
