### ISSUE TITLE
Implement functionality to add, edit and delete tasks in Todo Screen

### ISSUE THREAD

**Issue by ManjunathRK1251** [gdsc-jssstu/student_study_manager#4]
## Implement the following functionalities
- User should be able to add the new items to 'Todo screen'
- User should be able to dismiss/delete finished tasks
- User should be able to edit the existing tasks

**Comment by iamvermajayant** [comment]
hey I would like to work on this issue

**Comment by ShivamMenda** [comment]
@

**Comment by rktejesh** [comment]
Hi @ManjunathRK1251 
Can I work on this issue?

**Comment by ManjunathRK1251** [comment]
Hey @rktejesh , sure go ahead!!
All the best :)

**Comment by ShivamMenda** [comment]
@rktejesh any update?

**Comment by ShivamMenda** [comment]
Last day today @rktejesh Open a PR so I can review the PR and merge by tomorrow.

**Comment by prithvi206** [comment]
@ShivamMenda can you assign me

**Comment by ShivamMenda** [comment]
@prithvi206 Go ahead! Submit it asap you have 2 hours to go.

**Comment by ShivamMenda** [comment]
#21 solves this issue.
