### ISSUE TITLE
In 'Add timetable' screen : add functionality to upload images to the app via Camera and via Gallery

### ISSUE THREAD

**Issue by ManjunathRK1251** [gdsc-jssstu/student_study_manager#5]
## Refer to 'Add timetable' screen
- In that implement functionality which allows the user to access the images from the Gallery or click pictures using the device camera
- After accessing the images, upload them to the app
- When the user opens the app next time, the images should be displayed in the app.

**Comment by SamuelBasseyJohn** [comment]
Hello, Please can i take on this issue

**Comment by saurav0523** [comment]
I would like to contribute in this issue.

**Comment by ShivamMenda** [comment]
@saurav0523 Sure go ahead! All the best!

**Comment by saurav0523** [comment]
@ShivamMenda thank you sir

**Comment by ShivamMenda** [comment]
@saurav0523 Any update?

**Comment by prithvi206** [comment]
@ShivamMenda can you assign me this ?

**Comment by ShivamMenda** [comment]
@saurav0523 As it's been 9 days with no update, I'm going to have to remove you from the issue.

**Comment by ShivamMenda** [comment]
@prithvi206 I'll be assigning this issue to you. Please do work on it.

**Comment by ShivamMenda** [comment]
#18 is the PR opened. Everything is resolved.
