### ISSUE TITLE
In 'Add notes' screen : Implement the functionality to upload documents to the app

### ISSUE THREAD

**Issue by ManjunathRK1251** [gdsc-jssstu/student_study_manager#7]
## Refer to the 'Add notes' screen

- Add permission to access the documents from the device
- Users should be able to upload their documents from their devices to the app

**Comment by prithvi206** [comment]
@ShivamMenda can  you assign this issue for me.

**Comment by ShivamMenda** [comment]
@prithvi206 Yes sure go ahead!

**Comment by ShivamMenda** [comment]
@prithvi206 Any Update?

**Comment by prithvi206** [comment]
@ShivamMenda On it, resolving some errors.

**Comment by ShivamMenda** [comment]
@prithvi206 Sure! Open a PR when ready.

**Comment by ShivamMenda** [comment]
Last day today @prithvi206 Open a PR so I can review the PR and merge by tomorrow.

**Comment by ShivamMenda** [comment]
This issue is resolved!
