### ISSUE TITLE
UI Implementation of 'My dashboard' and 'Todo lists' screens

### ISSUE THREAD

**Issue by ManjunathRK1251** [gdsc-jssstu/student_study_manager#8]

**Comment by ShivamMenda** [comment]
@SahadevaMK Do you want to work on this issue? Should I assign you this?

**Comment by UtkarshDeoli** [comment]
please provide more information

**Comment by ShivamMenda** [comment]
@UtkarshDeoli So if you look in our Read me files we've kept proposed design of the screens in this case the Todo screen and dashboard. You've to replicate this design that's all.

**Comment by UtkarshDeoli** [comment]
Ok can u please assign this to me 
And is it possible to make these two UI screens into different 2 Issues insted of one

**Comment by tanyaa-arora** [comment]
HI @ShivamMenda Can you assign this issue to me?

**Comment by ShivamMenda** [comment]
@UtkarshDeoli As all the other issues have two screens and the add tasks screen is fairly simple I think we are going to go with two. Please let us know asap if not I'll assign the issue to @tanyaa-arora

**Comment by ShivamMenda** [comment]
> HI @ShivamMenda Can you assign this issue to me?
> 
> 

@tanyaa-arora Thank you so much for the enthusiasm. We will wait for @UtkarshDeoli 's reply and if he's not working on it I will assign the issue to you.
Please do check out other issues there's a lot of open ones with UI implementation if you aren't getting this issue. 
Thank you and happy open Sourcing.

**Comment by ShivamMenda** [comment]
@UtkarshDeoli I really love that you're taking up issues and enthusiastic. If it's okay with you can I assign this to @tanyaa-arora ? As you've already got two issues, I think @tanyaa-arora can work on this. But it's your call as you were here first. If you can handle all the 3 issues I'll assign this to you if not I'll assign this to @tanyaa-arora Let me know asap.

**Comment by UtkarshDeoli** [comment]
that's fine @ShivamMenda assign it to @tanyaa-arora , let's make everyone participate , all the best @tanyaa-arora  
and thank you @ShivamMenda

**Comment by ShivamMenda** [comment]
Thank you so much @UtkarshDeoli! I wish you all the very best! @tanyaa-arora It's all yours I'll assign this issue to you.All the best!

**Comment by tanyaa-arora** [comment]
Hi @ShivamMenda, I'd like to withdraw from the issue. I did not go through the tech stack properly before and I do not have much knowledge of flutter. I apologize for the misunderstanding

**Comment by ShivamMenda** [comment]
@tanyaa-arora Okay sure no problem.

**Comment by ShivamMenda** [comment]
This issue is now open to be worked on

**Comment by UtkarshDeoli** [comment]
@ShivamMenda  Please Assign this to me

**Comment by ShivamMenda** [comment]
@UtkarshDeoli All yours! All the best!

**Comment by ShivamMenda** [comment]
@UtkarshDeoli Any Update?

**Comment by ShivamMenda** [comment]
@UtkarshDeoli If there's no update from your side I'll be assigning this issue to someone else. Please reply within a day asap if you still want to work on this.

**Comment by UtkarshDeoli** [comment]
i will do it by Tomarrow that os 27/10/2022

**Comment by ShivamMenda** [comment]
@UtkarshDeoli Sure! Open a PR when ready.

**Comment by ShivamMenda** [comment]
Last day today @UtkarshDeoli Open a PR so I can review the PR and merge by tomorrow.
